SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (max_data.MAX_SIZE - e.SIZE_OF_COLONY) AS YEAR_DEV,
    e.ID
FROM 
    ECOLI_DATA e
JOIN 
    (SELECT 
         YEAR(DIFFERENTIATION_DATE) AS YEAR, 
         MAX(SIZE_OF_COLONY) AS MAX_SIZE
     FROM 
         ECOLI_DATA
     GROUP BY 
         YEAR(DIFFERENTIATION_DATE)) max_data
ON 
    YEAR(e.DIFFERENTIATION_DATE) = max_data.YEAR
ORDER BY 
    YEAR ASC,
    YEAR_DEV ASC;